### ISSUE TITLE
No Browser section

### ISSUE THREAD

**Issue by eribertomota** [exeldro/obs-browser-transition#5]
Hi @exeldro,

I built the plugin out of tree on Debian. I can't see the Browser section shown in Andilippi's vídeo. I am using OBS 29 on Debian.

Please, see an attached image below. How I could help to debug? The log shows a full load of the plugin.

Thanks in advance.

![browser](https://user-images.githubusercontent.com/6435502/216793840-03b3dfc1-4f07-40e0-b826-a1db1c6a7de9.jpg)

**Comment by exeldro** [comment]
It looks like the private browser source did not load.
Do you have browser sources in obs?
Maybe the browser source has an other id on linux, on windows it is "browser_source"

**Comment by eribertomota** [comment]
Is this a source? I would see it as a common source? 

![sources](https://user-images.githubusercontent.com/6435502/216797034-c702af88-f5bb-4a65-9df0-9452c90869a8.jpg)

**Comment by exeldro** [comment]
This is the source it uses:
![image](https://user-images.githubusercontent.com/5457024/216829949-a248dfd1-88b8-4e76-a50d-a3b70b330fb2.png)
It should be part of OBS build with flags BUILD_BROWSER and ENABLE_BROWSER
Source code can be found here:
https://github.com/obsproject/obs-browser/

**Comment by eribertomota** [comment]
Right, this is not enabled in Debian. I will try to talk with the maintainer of the obs-studio on Debian. Thanks!
