### ISSUE TITLE
Ability to refresh browser transition from property option.

### ISSUE THREAD

**Issue by ilsubyeega** [exeldro/obs-browser-transition#6]
The official browser source supports refreshing the content/cache. However, I cannot find how to refresh the browser of obs-browser-transition at this moment. This may be good for whoever develops browser transition without running hot-reload.

obs-browser supports refreshing like this:
![image](https://github.com/exeldro/obs-browser-transition/assets/37479424/7abc8fb5-74fb-4658-bbff-e26b48d90185)

**Comment by exeldro** [comment]
Here is a version with a working refresh button in the properties:
https://github.com/exeldro/obs-browser-transition/actions/runs/6431818742
Let me know if that is what you want.

**Comment by ilsubyeega** [comment]
The new build works as expected, thank you for implementing this!
